### ISSUE TITLE
URL Structure of API is confusing

### ISSUE THREAD

**Issue by jbleduigou** [linto-ai/linto-platform-stt-service-manager#3]
Hi,

If I understand correctly the API, we have the following endpoints :
* GET http://localhost/services : list all services
* POST http://localhost/service/1337 : create a new service with id 1337

I find it rather confusing, is there any reason for not using one of the following for service creation ?

* POST http://localhost/services/1337 : create a new service with id 1337
* POST http://localhost/services : create a new service with id provided in payload

**Comment by jbleduigou** [comment]
Also we might want to introduce API versioning.

**Comment by damienlaine** [comment]
The API is documented with a swagger client that enables you to interact with the deployed API.

The "id" here is the technical name of the service itself (like, let's say linto_command_fr)

You can access the swagger client at this URL :
http(s)//${LINTO-STACK_DOMAIN}/stt-manager/api-doc/

Check documentation :

https://github.com/linto-ai/linto-platform-stack
